import { PageHeader } from './pageHeader'
import type { View } from '../types'
import { Icon } from '../utils'

export function AcademyView({ openModal, setActiveView }: { openModal: (title: string) => void; setActiveView: (view: View) => void }) {
  return <><PageHeader eyebrow="YOUR CLUB · 6 PLAYERS" title="Academy" description="6 youth players · Ranking: 4th of 18" action={<button className="primary-button" onClick={() => openModal('Youth tournament')}>Enter tournament <Icon>→</Icon></button>} /><div className="academy-hero panel"><div className="academy-copy"><span className="live-pill purple-pill">✦ ACADEMY SPOTLIGHT</span><h2>Academy spotlight</h2><p>Top prospects in the development pipeline. Performance data updates weekly.</p><div className="academy-progress"><div><span>ACADEMY RANKING</span><b>04 <small>of 18</small></b></div><div className="progress-track"><i /></div><small>Top 3 earns an invite to the National Youth Series</small></div></div><div className="academy-player"><div className="academy-portrait">IS</div><span className="academy-rating">68 <small>OVR</small></span><div className="academy-player-name"><span>U18 · CAM</span><b>Imani Sol</b><small>Scout confidence: high</small></div></div></div><div className="academy-grid"><section className="panel youth-list"><div className="panel-heading"><div><span className="section-kicker">YOUTH PIPELINE</span><h3>Players to watch</h3></div><button className="text-link" onClick={() => openModal('Full academy list')}>View all <Icon>→</Icon></button></div><YouthRow name="Imani Sol" detail="CAM · 17 yrs" rating="68" status="Breakthrough ready" color="#df7e68" progress={88} /><YouthRow name="Luca Neri" detail="LB · 16 yrs" rating="62" status="Building momentum" color="#769ddc" progress={61} /><YouthRow name="Sami Okafor" detail="ST · 15 yrs" rating="55" status="Early development" color="#5eb59c" progress={34} /></section><section className="panel academy-actions"><div className="panel-heading"><div><span className="section-kicker">PROGRAMS</span><h3>Shape the future</h3></div></div><button className="program-card" onClick={() => openModal('Academy coaching')}><span className="program-icon purple">♙</span><span><b>Coach assignments</b><small>3 staff available · 2 open roles</small></span><Icon>→</Icon></button><button className="program-card" onClick={() => openModal('Youth recruitment')}><span className="program-icon amber">⌕</span><span><b>Expand recruitment</b><small>Explore a new regional network</small></span><Icon>→</Icon></button><button className="program-card" onClick={() => setActiveView('squad')}><span className="program-icon cyan">↗</span><span><b>Promote a player</b><small>Move a prospect to senior training</small></span><Icon>→</Icon></button></section></div></>
}

export function YouthRow({ name, detail, rating, status, color, progress }: { name: string; detail: string; rating: string; status: string; color: string; progress: number }) {
  return <div className="youth-row"><div className="youth-avatar" style={{ background: color }}>{name.split(' ').map((word) => word[0]).join('')}</div><div className="youth-name"><b>{name}</b><small>{detail}</small></div><strong>{rating}</strong><div className="youth-progress"><span>{status}</span><div><i style={{ width: `${progress}%` }} /></div></div><Icon>›</Icon></div>
}

