import { PageHeader } from './pageHeader'
import type { Player, CareerProfile } from '../types'
import { formatMoney, Icon } from '../utils'

export function PlayerClubView({ profile, player, openModal }: { profile: CareerProfile; player: Player; openModal: (title: string) => void }) {
  return <><PageHeader eyebrow="PLAYER CAREER · CLUB LIFE" title="Club life" description={`${profile.clubName} · ${profile.playerPosition} · Contract: 4 years`} action={<button className="outline-button" onClick={() => openModal('Contract conversation')}><Icon>◎</Icon> Contract talk</button>} /><div className="player-club-grid"><section className="panel contract-card"><div className="panel-heading"><div><span className="section-kicker">YOUR DEAL</span><h3>Make the next move count.</h3></div><span className="finance-health">SECURE</span></div><div className="contract-player"><div className="player-profile-avatar" style={{ background: `linear-gradient(135deg, ${profile.primaryColor}, ${profile.secondaryColor})` }}>{profile.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div><div><b>{profile.name}</b><small>{profile.playerPosition} · {profile.clubName}</small></div><strong>{formatMoney(player.wage)}<small>PER WEEK</small></strong></div><div className="contract-grid"><div><span>CONTRACT</span><b>4 years</b></div><div><span>ROLE</span><b>Rotation</b></div><div><span>RELEASE VALUE</span><b>{formatMoney(player.value)}</b></div><div><span>MANAGER TRUST</span><b className="lime-text">74%</b></div></div><button className="primary-button full-button" onClick={() => openModal('Contract conversation')}>Discuss your role <Icon>→</Icon></button></section><section className="panel relationships-card"><div className="panel-heading"><div><span className="section-kicker">DRESSING ROOM</span><h3>People who shape your season</h3></div></div><div className="relationship-row"><div className="relationship-avatar" style={{ background: '#f07f5e' }}>NB</div><div><b>Nico Bellori</b><small>Training partner · CM</small></div><span className="relationship-score positive">86</span></div><div className="relationship-row"><div className="relationship-avatar" style={{ background: '#8a7dff' }}>RK</div><div><b>Rayan Kessler</b><small>Rival · CB</small></div><span className="relationship-score rival">63</span></div><div className="relationship-row"><div className="relationship-avatar" style={{ background: '#e8b74c' }}>LS</div><div><b>Lio Santoro</b><small>Senior mentor · AM</small></div><span className="relationship-score positive">79</span></div><button className="text-link" onClick={() => openModal('Social choices')}>Open social choices <Icon>→</Icon></button></section><section className="panel club-standing-card"><span className="section-kicker">CLUB STANDING</span><h2>{profile.clubName}</h2><p>You are currently competing for a place in the matchday squad. Your next objective is simple: complete 3 strong training sessions before selection.</p><div className="standing-track"><i style={{ width: '68%' }} /></div><div className="standing-footer"><span>ROTATION PLAYER</span><b>68% to first-team lock</b></div></section></div></>
}

export function ClubView({ budget, requestInvestment, openModal }: { budget: number; requestInvestment: () => void; openModal: (title: string) => void }) {
  return <><PageHeader eyebrow="CLUB VISION · 2026—2030" title="Club vision" description={`Board confidence: 86% · Financial status: Healthy`} action={<button className="outline-button" onClick={() => openModal('Club roadmap')}><Icon>▦</Icon> Roadmap</button>} /><div className="vision-grid"><section className="panel vision-card primary-vision"><div className="vision-number">01</div><span className="section-kicker">BOARD MANDATE</span><h2>Board mandate</h2><p>Qualify for continental competition while maintaining youth development standards. The board supports the current strategy.</p><div className="objective-score"><div><span>BOARD CONFIDENCE</span><b>86%</b></div><div className="score-track"><i /></div><small>+12 since the start of the season</small></div></section><section className="panel finance-card"><div className="panel-heading"><div><span className="section-kicker">FINANCIAL CONTROL</span><h3>Every choice compounds.</h3></div><span className="finance-health">HEALTHY</span></div><div className="finance-total"><span>TRANSFER BALANCE</span><strong>{formatMoney(budget)}</strong><small>Updated after last window activity</small></div><div className="finance-bars"><FinanceBar label="Squad wages" value="€1.84M" percent={64} color="purple" /><FinanceBar label="Scouting network" value="€420K" percent={28} color="cyan" /><FinanceBar label="Facilities" value="€680K" percent={42} color="amber" /></div><button className="outline-button full-button" onClick={requestInvestment}>Request board investment <Icon>→</Icon></button></section><section className="panel values-card"><div className="panel-heading"><div><span className="section-kicker">CLUB DNA</span><h3>What we stand for</h3></div><button className="more-button">•••</button></div><div className="value-row"><span className="value-symbol purple">✦</span><div><b>Brave football</b><small>Possession with purpose</small></div><strong>92</strong></div><div className="value-row"><span className="value-symbol lime">♙</span><div><b>Grow our own</b><small>Academy pathway first</small></div><strong>87</strong></div><div className="value-row"><span className="value-symbol amber">◈</span><div><b>One city, one club</b><small>Community always</small></div><strong>95</strong></div></section></div></>
}

export function FinanceBar({ label, value, percent, color }: { label: string; value: string; percent: number; color: string }) {
  return <div className="finance-bar"><div><span>{label}</span><b>{value}</b></div><div className="finance-track"><i className={color} style={{ width: `${percent}%` }} /></div></div>
}

