import { formatMoney } from "../utils"
import { PageHeader } from './pageHeader'
import type { Prospect } from '../types'
import { Icon } from '../utils'

export function MarketView({ filteredProspects, search, setSearch, marketFilter, setMarketFilter, shortlist, scouted, negotiations, toggleShortlist, scoutProspect, startNegotiation, budget, openModal }: { filteredProspects: Prospect[]; search: string; setSearch: (value: string) => void; marketFilter: 'All' | 'Shortlist' | 'Scouted'; setMarketFilter: (value: 'All' | 'Shortlist' | 'Scouted') => void; shortlist: number[]; scouted: number[]; negotiations: number[]; toggleShortlist: (id: number) => void; scoutProspect: (id: number) => void; startNegotiation: (id: number) => void; budget: number; openModal: (title: string) => void }) {
  return <><PageHeader eyebrow="TRANSFER HUB · WINDOW OPEN" title="Transfer hub" description={`Budget: ${formatMoney(budget)} · Window open`} action={<div className="budget-pill"><span>AVAILABLE TO SPEND</span><b>{formatMoney(budget)}</b><Icon>€</Icon></div>} /><div className="market-toolbar panel"><div className="market-tabs"><button className={marketFilter === 'All' ? 'active' : ''} onClick={() => setMarketFilter('All')}>Discover <span>24</span></button><button className={marketFilter === 'Shortlist' ? 'active' : ''} onClick={() => setMarketFilter('Shortlist')}>Shortlist <span>{shortlist.length}</span></button><button className={marketFilter === 'Scouted' ? 'active' : ''} onClick={() => setMarketFilter('Scouted')}>Reports ready <span>{scouted.length}</span></button></div><label className="search-box"><Icon>⌕</Icon><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search player, position or club" /><kbd>⌘ K</kbd></label><button className="filter-button" onClick={() => openModal('Advanced filters')}><Icon>≡</Icon> Filters <span>2</span></button></div><div className="market-summary"><div><b>{filteredProspects.length === 0 ? 'No' : filteredProspects.length}</b><span>targets matching your profile</span></div><div className="summary-separator" /><div><span>Recruitment brief</span><b className="brief-tag">U21 · high potential · attack</b></div><button className="text-link" onClick={() => openModal('Recruitment brief')}>Edit brief <Icon>→</Icon></button></div><div className="prospect-grid">{filteredProspects.map((prospect) => <ProspectCard key={prospect.id} prospect={prospect} isShortlisted={shortlist.includes(prospect.id)} isScouted={scouted.includes(prospect.id)} isNegotiating={negotiations.includes(prospect.id)} toggleShortlist={toggleShortlist} scoutProspect={scoutProspect} startNegotiation={startNegotiation} />)}</div>{filteredProspects.length === 0 && <div className="empty-state panel"><div>⌕</div><h3>No targets found</h3><p>Try a wider search or switch back to Discover.</p></div>}</>
}

export function ProspectCard({ prospect, isShortlisted, isScouted, isNegotiating, toggleShortlist, scoutProspect, startNegotiation }: { prospect: Prospect; isShortlisted: boolean; isScouted: boolean; isNegotiating: boolean; toggleShortlist: (id: number) => void; scoutProspect: (id: number) => void; startNegotiation: (id: number) => void }) {
  return <article className="prospect-card panel"><div className="prospect-top"><span className="prospect-id">SCOUT 0{prospect.id - 100}</span><button className={`star-button ${isShortlisted ? 'starred' : ''}`} onClick={() => toggleShortlist(prospect.id)} aria-label="Toggle shortlist">★</button></div><div className="prospect-portrait" style={{ background: `linear-gradient(140deg, ${prospect.color}, #1a2740)` }}><span>{prospect.name.split(' ').map((word) => word[0]).join('')}</span><div className="country-badge">{prospect.flag}</div></div><div className="prospect-main"><div className="prospect-title"><div><h3>{prospect.name}</h3><span>{prospect.club} · {prospect.age} yrs</span></div><b className="prospect-rating">{prospect.rating}</b></div><div className="prospect-meta"><span className="position-chip">{prospect.position}</span><span><small>POTENTIAL</small><b>{prospect.potential}</b></span><span><small>VALUE</small><b>{prospect.value}</b></span></div><div className="tag-row">{prospect.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="interest-row"><span>PLAYER INTEREST</span><strong className={prospect.interest === 'Very high' ? 'very-high' : ''}><i />{prospect.interest}</strong></div></div><div className="prospect-actions"><button className="outline-button" onClick={() => scoutProspect(prospect.id)}>{isScouted ? 'Report ready' : 'Request report'} <Icon>{isScouted ? '✓' : '→'}</Icon></button><button className="primary-button" onClick={() => startNegotiation(prospect.id)}>{isNegotiating ? 'Negotiating' : 'Enquire'} <Icon>{isNegotiating ? '✓' : '↗'}</Icon></button></div></article>
}

