import { useState } from 'react'
import type { CSSProperties, FormEvent } from 'react'
import type { CareerMode, Position, CareerProfile, ClubOffer, OnboardingSave } from '../types'
import { formatMoney, createLegacyClubOffer, Icon } from '../utils'
export function ClubOffersView({ onboarding, onAccept }: { onboarding: OnboardingSave; onAccept: (offer: ClubOffer) => void }) {
  return <div className="setup-shell"><header className="setup-brand"><div className="brand-hex">NS</div><div><b>NORTHSTAR FC</b><small>CAREER MODE</small></div></header><main className="setup-card offers-card"><div className="setup-intro"><span className="live-pill"><i /> CLUB OFFERS</span><span className="section-kicker">SEASON 01 · YOUR FIRST APPOINTMENT</span><h1>Club offers</h1><p>{onboarding.name}, three clubs have submitted offers for your appointment. Review each one before deciding.</p></div><div className="offer-grid">{onboarding.offers.map((offer, index) => <article className="club-offer" key={offer.id} style={{ '--offer-primary': offer.primaryColor, '--offer-secondary': offer.secondaryColor } as CSSProperties}><div className="offer-topline"><span className="offer-index">0{index + 1}</span><span className="offer-league">{offer.league}</span></div><div className="offer-crest">{offer.clubShort}</div><span className="offer-identity">{offer.identity}</span><h2>{offer.clubName}</h2><p>{offer.description}</p><div className="offer-meta"><span><b>STYLE</b>{offer.philosophy}</span><span><b>{onboarding.mode === 'manager' ? 'BUDGET' : 'PATHWAY'}</b>{onboarding.mode === 'manager' ? formatMoney(offer.managerBudget) : offer.playerRole}</span></div><div className="offer-tradeoffs"><div><b>ADVANTAGES</b>{offer.pros.map((item) => <span key={item}>+ {item}</span>)}</div><div><b>TRADE-OFFS</b>{offer.cons.map((item) => <span key={item}>− {item}</span>)}</div></div><button className="primary-button full-button" onClick={() => onAccept(offer)}>{onboarding.acceptedOffer?.id === offer.id ? 'Continue with this club' : `Accept ${offer.clubName}`} <Icon>→</Icon></button></article>)}</div><div className="setup-footer"><span>Offers are locked to this career and saved locally.</span><span>{onboarding.mode === 'manager' ? 'Manager appointment' : 'Player contract'} · Season 1</span></div></main></div>
}

export function IntroductionView({ profile, offer, onContinue }: { profile: CareerProfile; offer: ClubOffer | null; onContinue: () => void }) {
  const acceptedOffer = offer ?? createLegacyClubOffer(profile)
  const isManager = profile.mode === 'manager'
  return <div className="setup-shell"><header className="setup-brand"><div className="brand-hex">NS</div><div><b>NORTHSTAR FC</b><small>CAREER MODE</small></div></header><main className="setup-card introduction-card"><div className="intro-scoreboard"><span>SEASON 01</span><b>WEEK 01</b><span>{acceptedOffer.league.toUpperCase()}</span></div><div className="setup-intro"><span className="live-pill"><i /> APPOINTMENT CONFIRMED</span><span className="section-kicker">THE OPENING BRIEFING</span><h1>{acceptedOffer.clubName}</h1><p>{isManager ? 'You have been appointed manager. Expectations are clear: establish an identity and deliver results.' : 'Your contract is signed. Training performance will determine how quickly you break into the first team.'}</p></div><div className="introduction-grid"><div className="introduction-club" style={{ background: `linear-gradient(135deg, ${acceptedOffer.primaryColor}, ${acceptedOffer.secondaryColor})` }}><span>{acceptedOffer.clubShort}</span><div><b>{acceptedOffer.clubName}</b><small>{acceptedOffer.identity} · {acceptedOffer.philosophy}</small></div></div><div className="introduction-brief"><span className="section-kicker">{isManager ? 'BOARD MANDATE' : 'FIRST-TEAM BRIEF'}</span><b>{isManager ? 'Make the club competitive without losing its identity.' : `Earn a role as a ${acceptedOffer.playerRole.toLowerCase()} and make every training session count.`}</b><div className="tag-row"><span>{acceptedOffer.pros[0]}</span><span>{acceptedOffer.cons[0]}</span></div></div></div><button className="primary-button setup-submit" onClick={onContinue}>Enter {acceptedOffer.clubName} <Icon>→</Icon></button><div className="setup-footer"><span>Season 1 · Week 1 · Day 1</span><span>Career state saves automatically</span></div></main></div>
}

export function SetupView({ onComplete }: { onComplete: (onboarding: OnboardingSave) => void }) {
  const [mode, setMode] = useState<CareerMode>('manager')
  const [name, setName] = useState('Jules Park')
  const [league, setLeague] = useState('Premier Division')
  const [difficulty, setDifficulty] = useState('Authentic')
  const [playerPosition, setPlayerPosition] = useState<Position>('AM')

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    onComplete({ mode, name: name.trim() || 'Jules Park', leaguePreference: league, difficulty, playerPosition, offers: [] })
  }

  return <div className="setup-shell"><header className="setup-brand"><div className="brand-hex">NS</div><div><b>NORTHSTAR FC</b><small>CAREER MODE</small></div></header><main className="setup-card"><div className="setup-intro"><span className="live-pill"><i /> NEW CAREER</span><span className="section-kicker">SEASON 01 · FRESH APPOINTMENT</span><h1>Start your career</h1><p>Choose your path, name, and starting conditions. Every decision shapes your story.</p></div><form onSubmit={submit}><div className="setup-grid"><div className="setup-field"><span>CAREER MODE</span><div className="mode-toggle"><button type="button" className={mode === 'manager' ? 'active' : ''} onClick={() => setMode('manager')}><span className="setup-option-icon" style={{ color: '#00d4ff', background: 'rgba(0,212,255,.1)' }}>⚑</span><span><b>Manager career</b><small>Lead the club from the touchline</small></span></button><button type="button" className={mode === 'player' ? 'active' : ''} onClick={() => setMode('player')}><span className="setup-option-icon" style={{ color: '#4cf051', background: 'rgba(76,240,81,.1)' }}>★</span><span><b>Player career</b><small>Control your own destiny</small></span></button></div></div><div className="setup-field"><span>YOUR NAME</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Enter your name" maxLength={40} /></div><div className="setup-field"><span>PREFERRED LEAGUE</span><select value={league} onChange={(e) => setLeague(e.target.value)}><option>Premier Division</option><option>Continental League</option><option>Coastal Championship</option><option>Alpine League</option></select></div><div className="setup-field"><span>DIFFICULTY</span><select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}><option>Authentic</option><option>Challenging</option><option>Standard</option></select></div><div className="setup-field"><span>PLAYER POSITION</span><select value={playerPosition} onChange={(e) => setPlayerPosition(e.target.value as Position)}>{(mode === 'player' ? ['AM', 'ST', 'LW', 'RW', 'CM', 'DM', 'CB', 'LB', 'RB', 'GK'] : ['AM', 'ST', 'LW', 'RW', 'CM', 'CB']).map((p) => <option key={p}>{p}</option>)}</select></div></div><div className="club-customizer"><div><small>CLUB STYLE</small><b>Generated from league selection</b></div><div className="kit-preview" style={{ background: 'linear-gradient(135deg,#0ea5e9,#1f8a5f)', color: '#fff' }}>NS</div></div><button type="submit" className="setup-submit">Generate club offers <Icon>→</Icon></button></form><div className="setup-footer"><span>All progress saves automatically</span><span>Season 1 · Aug 2026</span></div></main></div>
}


