import { PageHeader } from './pageHeader'
import type { Player, View } from '../types'
import { positionColors } from '../data'
import { formatMoney, Icon } from '../utils'

export function SquadView({ players, selectedPlayer, setSelectedPlayerId, openModal }: { players: Player[]; selectedPlayer: Player; setSelectedPlayerId: (id: number) => void; openModal: (title: string) => void }) {
  return <><PageHeader eyebrow="SQUAD MANAGEMENT · 13 PLAYERS" title="Squad management" description={`${players.length} players · Squad rating: ${(players.reduce((t, p) => t + p.rating, 0) / players.length).toFixed(0)}`} action={<button className="outline-button" onClick={() => openModal('Team tactics')}><Icon>◎</Icon> Team tactics</button>} /><div className="squad-layout"><section className="panel squad-list-panel"><div className="squad-toolbar"><div className="filter-tabs"><button className="active">All players <span>13</span></button><button>Starting XI <span>11</span></button><button>Development <span>4</span></button></div><button className="select-button">Sort: OVR <Icon>⌄</Icon></button></div><div className="player-table"><div className="table-head"><span>PLAYER</span><span>POS</span><span>OVR</span><span>FORM</span><span>FITNESS</span><span>ROLE</span><span /></div>{players.map((player) => <button className={`player-row ${selectedPlayer.id === player.id ? 'selected' : ''}`} key={player.id} onClick={() => setSelectedPlayerId(player.id)}><div className="player-cell"><div className="player-avatar" style={{ background: player.color }}>{player.initials}</div><div><b>{player.name}</b><small>{player.age} yrs · {player.contract} yr contract</small></div></div><span className="position-chip">{player.position}</span><strong className="rating-number">{player.rating}</strong><span className={`form-value ${player.form >= 85 ? 'hot' : ''}`}><i />{player.form}</span><span className="fitness-bar"><i style={{ width: `${player.fitness}%` }} /><small>{player.fitness}%</small></span><span className="role-text">{player.role}</span><Icon>›</Icon></button>)}</div></section><PlayerDetail player={selectedPlayer} openModal={openModal} /></div></>
}

export function PlayerDetail({ player, openModal }: { player: Player; openModal: (title: string) => void }) {
  return <aside className="panel player-detail"><div className="detail-cover" style={{ background: `linear-gradient(135deg, ${player.color}, #162137 78%)` }}><span className="detail-number">{String(player.id).padStart(2, '0')}</span><div className="detail-avatar">{player.initials}</div><div className="detail-name"><span>{player.position} · {player.age} YEARS</span><h2>{player.name}</h2><small>Your Club · Since 2024</small></div></div><div className="detail-body"><div className="detail-rating"><div><span>OVERALL</span><strong>{player.rating}</strong></div><div><span>POTENTIAL</span><strong className="potential">{player.potential}</strong></div><div><span>MARKET VALUE</span><strong>{formatMoney(player.value)}</strong></div></div><div className="detail-section"><div className="detail-section-title"><b>Form & fitness</b></div><div className="dynamic-bars"><DynamicBar label="Form" value={player.form} color="purple" /><DynamicBar label="Morale" value={player.morale} color="lime" /><DynamicBar label="Match fitness" value={player.fitness} color="cyan" /></div></div><div className="detail-section attributes"><div className="detail-section-title"><b>Key attributes</b><button className="text-link">Full profile <Icon>→</Icon></button></div><div className="attribute-grid"><span>PACE <b>{player.position === 'ST' ? 91 : 78}</b></span><span>SHOOTING <b>{player.position === 'ST' ? 94 : 69}</b></span><span>PASSING <b>{player.position === 'ST' ? 78 : 84}</b></span><span>DEFENDING <b>{player.position === 'CB' ? 88 : 42}</b></span></div></div><div className="detail-actions"><button className="primary-button" onClick={() => openModal(`Develop ${player.name}`)}>Set development <Icon>→</Icon></button><button className="square-button" onClick={() => openModal(`Player actions: ${player.name}`)}>•••</button></div></div></aside>
}

export function DynamicBar({ label, value, color }: { label: string; value: number; color: string }) {
  return <div className="dynamic-row"><div><span>{label}</span><b>{value}</b></div><div className="dynamic-track"><i className={color} style={{ width: `${value}%` }} /></div></div>
}

